MATH_GRAPH_GROUPS = [
    {"label": "Primary Math", "x": 28},
    {"label": "Lower Secondary", "x": 330},
    {"label": "Algebra and Functions", "x": 650},
    {"label": "Precalculus", "x": 970},
    {"label": "Limits and Continuity", "x": 1290},
    {"label": "Calculus 1", "x": 1570},
    {"label": "Calculus 2", "x": 1845},
    {"label": "Calculus 3", "x": 2070},
]

SUBJECTS = [
    {
        "code": "math",
        "name": "Mathematics",
        "description": "Calculus-oriented prerequisite graph aligned with the current mobile knowledge-map mock.",
        "display_order": 1,
        "metadata": {
            "graph": {
                "title": "Mathematics Prerequisite Map",
                "width": 2260,
                "height": 600,
                "top_down": True,
                "groups": MATH_GRAPH_GROUPS,
            }
        },
    },
    {
        "code": "physics",
        "name": "Physics",
        "description": "Subject catalog entry reserved for future graph seeding.",
        "display_order": 2,
        "metadata": {},
    },
    {
        "code": "chemistry",
        "name": "Chemistry",
        "description": "Subject catalog entry reserved for future graph seeding.",
        "display_order": 3,
        "metadata": {},
    },
    {
        "code": "biology",
        "name": "Biology",
        "description": "Subject catalog entry reserved for future graph seeding.",
        "display_order": 4,
        "metadata": {},
    },
]

MATH_CONCEPTS = [
    {
        "code": "counting",
        "title": "Counting",
        "x": 28,
        "y": 82,
        "status": "mastered",
        "grade_band": "primary",
    },
    {
        "code": "place_value",
        "title": "Place Value",
        "x": 28,
        "y": 152,
        "status": "mastered",
        "grade_band": "primary",
    },
    {
        "code": "operations",
        "title": "Arithmetic Operations",
        "x": 28,
        "y": 222,
        "status": "mastered",
        "grade_band": "primary",
    },
    {
        "code": "fractions",
        "title": "Fractions and Decimals",
        "x": 28,
        "y": 292,
        "status": "mastered",
        "grade_band": "primary",
    },
    {
        "code": "geometry_basic",
        "title": "Basic Shapes and Measurement",
        "x": 28,
        "y": 362,
        "status": "mastered",
        "grade_band": "primary",
    },
    {
        "code": "data_basic",
        "title": "Tables, Charts, and Mean",
        "x": 28,
        "y": 432,
        "status": "ready",
        "grade_band": "primary",
    },
    {
        "code": "integers",
        "title": "Integers and Rational Numbers",
        "x": 330,
        "y": 82,
        "status": "mastered",
        "grade_band": "lower_secondary",
    },
    {
        "code": "exponents_basic",
        "title": "Exponents and Roots Basics",
        "x": 330,
        "y": 152,
        "status": "mastered",
        "grade_band": "lower_secondary",
    },
    {
        "code": "linear_equations",
        "title": "Linear Equations",
        "x": 330,
        "y": 222,
        "status": "mastered",
        "grade_band": "lower_secondary",
    },
    {
        "code": "coordinate_graphing",
        "title": "Coordinate Graphing",
        "x": 330,
        "y": 292,
        "status": "mastered",
        "grade_band": "lower_secondary",
    },
    {
        "code": "slope",
        "title": "Slope and Intercepts",
        "x": 330,
        "y": 362,
        "status": "review",
        "grade_band": "lower_secondary",
    },
    {
        "code": "pythagorean",
        "title": "Pythagorean Theorem",
        "x": 330,
        "y": 432,
        "status": "ready",
        "grade_band": "lower_secondary",
    },
    {
        "code": "functions",
        "title": "Functions, Domain, and Range",
        "x": 650,
        "y": 82,
        "status": "mastered",
        "grade_band": "algebra",
    },
    {
        "code": "composition",
        "title": "Function Composition and Inverses",
        "x": 650,
        "y": 152,
        "status": "review",
        "grade_band": "algebra",
    },
    {
        "code": "exponential_log",
        "title": "Exponential and Logarithmic Functions",
        "x": 650,
        "y": 222,
        "status": "ready",
        "grade_band": "algebra",
    },
    {
        "code": "quadratics",
        "title": "Quadratic and Polynomial Functions",
        "x": 650,
        "y": 292,
        "status": "mastered",
        "grade_band": "algebra",
    },
    {
        "code": "rational_functions",
        "title": "Rational Functions",
        "x": 650,
        "y": 362,
        "status": "ready",
        "grade_band": "algebra",
    },
    {
        "code": "sequences",
        "title": "Sequences, Series, Sigma Notation",
        "x": 650,
        "y": 432,
        "status": "ready",
        "grade_band": "algebra",
    },
    {
        "code": "analytic_geometry",
        "title": "Analytic Geometry and Conics",
        "x": 970,
        "y": 82,
        "status": "ready",
        "grade_band": "precalculus",
    },
    {
        "code": "trig_functions",
        "title": "Trigonometric Functions and Graphs",
        "x": 970,
        "y": 152,
        "status": "ready",
        "grade_band": "precalculus",
    },
    {
        "code": "trig_identities",
        "title": "Trigonometric Identities and Equations",
        "x": 970,
        "y": 222,
        "status": "locked",
        "grade_band": "precalculus",
    },
    {
        "code": "vectors_basic",
        "title": "Vectors, Parametric, and Polar Basics",
        "x": 970,
        "y": 292,
        "status": "ready",
        "grade_band": "precalculus",
    },
    {
        "code": "precalc_fluency",
        "title": "Precalculus Fluency",
        "x": 970,
        "y": 362,
        "status": "active",
        "grade_band": "precalculus",
    },
    {
        "code": "intuitive_limits",
        "title": "Intuitive Limits",
        "x": 1290,
        "y": 102,
        "status": "active",
        "grade_band": "limits_and_continuity",
    },
    {
        "code": "limit_laws",
        "title": "Limit Laws and Algebraic Techniques",
        "x": 1290,
        "y": 172,
        "status": "ready",
        "grade_band": "limits_and_continuity",
    },
    {
        "code": "trig_limits",
        "title": "Trigonometric Limits and Squeeze Theorem",
        "x": 1290,
        "y": 242,
        "status": "locked",
        "grade_band": "limits_and_continuity",
    },
    {
        "code": "continuity",
        "title": "Continuity and Intermediate Value Theorem",
        "x": 1290,
        "y": 312,
        "status": "ready",
        "grade_band": "limits_and_continuity",
    },
    {
        "code": "derivative_definition",
        "title": "Derivative Definition",
        "x": 1570,
        "y": 72,
        "status": "ready",
        "grade_band": "calculus_1",
    },
    {
        "code": "derivative_rules",
        "title": "Derivative Rules",
        "x": 1570,
        "y": 142,
        "status": "locked",
        "grade_band": "calculus_1",
    },
    {
        "code": "chain_rule",
        "title": "Chain Rule and Implicit Differentiation",
        "x": 1570,
        "y": 212,
        "status": "locked",
        "grade_band": "calculus_1",
    },
    {
        "code": "applications_derivatives",
        "title": "Related Rates, Optimization, Curve Sketching",
        "x": 1570,
        "y": 282,
        "status": "locked",
        "grade_band": "calculus_1",
    },
    {
        "code": "basic_integrals",
        "title": "Antiderivatives, Riemann Sums, Definite Integrals",
        "x": 1570,
        "y": 352,
        "status": "locked",
        "grade_band": "calculus_1",
    },
    {
        "code": "ftc",
        "title": "Fundamental Theorem of Calculus",
        "x": 1570,
        "y": 422,
        "status": "locked",
        "grade_band": "calculus_1",
    },
    {
        "code": "integration_techniques",
        "title": "Integration Techniques",
        "x": 1845,
        "y": 102,
        "status": "locked",
        "grade_band": "calculus_2",
    },
    {
        "code": "integral_applications",
        "title": "Area, Volume, Work, Fluid Force",
        "x": 1845,
        "y": 172,
        "status": "locked",
        "grade_band": "calculus_2",
    },
    {
        "code": "calculus_series",
        "title": "Convergence Tests and Power Series",
        "x": 1845,
        "y": 242,
        "status": "locked",
        "grade_band": "calculus_2",
    },
    {
        "code": "parametric_polar",
        "title": "Parametric and Polar Calculus",
        "x": 1845,
        "y": 312,
        "status": "locked",
        "grade_band": "calculus_2",
    },
    {
        "code": "vectors_3d",
        "title": "3D Coordinates and Vector Operations",
        "x": 2070,
        "y": 102,
        "status": "locked",
        "grade_band": "calculus_3",
    },
    {
        "code": "partial_derivatives",
        "title": "Partial Derivatives and Gradients",
        "x": 2070,
        "y": 172,
        "status": "locked",
        "grade_band": "calculus_3",
    },
    {
        "code": "multiple_integrals",
        "title": "Double and Triple Integrals",
        "x": 2070,
        "y": 242,
        "status": "locked",
        "grade_band": "calculus_3",
    },
    {
        "code": "vector_calculus",
        "title": "Vector Fields, Line Integrals, Green, Stokes, Divergence",
        "x": 2070,
        "y": 312,
        "status": "locked",
        "grade_band": "calculus_3",
    },
]

MATH_EDGES = [
    ("counting", "place_value"),
    ("place_value", "operations"),
    ("operations", "fractions"),
    ("operations", "integers"),
    ("fractions", "integers"),
    ("fractions", "linear_equations"),
    ("geometry_basic", "pythagorean"),
    ("data_basic", "sequences"),
    ("integers", "linear_equations"),
    ("exponents_basic", "exponential_log"),
    ("linear_equations", "slope"),
    ("coordinate_graphing", "slope"),
    ("slope", "functions"),
    ("functions", "composition"),
    ("functions", "quadratics"),
    ("quadratics", "rational_functions"),
    ("exponential_log", "trig_functions"),
    ("composition", "precalc_fluency"),
    ("rational_functions", "precalc_fluency"),
    ("sequences", "calculus_series"),
    ("pythagorean", "analytic_geometry"),
    ("analytic_geometry", "vectors_basic"),
    ("trig_functions", "trig_identities"),
    ("trig_identities", "trig_limits"),
    ("vectors_basic", "parametric_polar"),
    ("precalc_fluency", "intuitive_limits"),
    ("intuitive_limits", "limit_laws"),
    ("limit_laws", "continuity"),
    ("trig_limits", "derivative_rules"),
    ("continuity", "derivative_definition"),
    ("derivative_definition", "derivative_rules"),
    ("derivative_rules", "chain_rule"),
    ("chain_rule", "applications_derivatives"),
    ("derivative_rules", "basic_integrals"),
    ("basic_integrals", "ftc"),
    ("ftc", "integration_techniques"),
    ("integration_techniques", "integral_applications"),
    ("integration_techniques", "calculus_series"),
    ("parametric_polar", "vectors_3d"),
    ("vectors_3d", "partial_derivatives"),
    ("partial_derivatives", "multiple_integrals"),
    ("multiple_integrals", "vector_calculus"),
]
